[package]
name = "exe_who"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.3.1"
memexec = "0.2"
enigo = "0.0.14"
ctrlc = "3.2.3"
walkdir = "2.2.9" 
colored = "2.0.0"
reqwest = { version = "0.11"}
tokio = { version = "1", features = ["full"] }

[dependencies.windows]
version = "0.43.0"
features = [
    "Win32_System_Memory", 
    "Win32_System_LibraryLoader",
    "Win32_Foundation"
]
